//Not available from J. Stiller, so created myself.

AliAnalysisTaskSEBpmMass *AddTaskSEBpmMass(
                                TString cutsfile="",
                                TString usercomment = "doremalen",
                                Bool_t bUseMCInfo=kFALSE,
                                Bool_t performRotation = kFALSE,
                                Int_t nDegreePerRotation=3,
                                Int_t nNumberOfRotations=0,
                                Bool_t useCentrality=kFALSE,
                                Bool_t isHIJING = kFALSE,
                                Bool_t isHIJINGonly = kFALSE,
                                Bool_t killCandidates = kTRUE
                                )
{
  
  AliAnalysisManager *mgr = AliAnalysisManager::GetAnalysisManager();

  // gDebug = 1;
  if (!mgr) {
    ::Error("AddTaskBPlustoD0Pi1", "No analysis manager to connect to.");
    return NULL;
  }

  // cuts are stored in a TFile generated by makeTFile4CutsBPlustoD0Pi1.C in ./macros/
  // set the cuts there!

  TFile* filecuts;
  if( cutsfile.EqualTo("") ) {
    ::Error("Input file not found : add a cut object","");
  } else {
      filecuts=TFile::Open(cutsfile.Data());
      if(!filecuts ||(filecuts && !filecuts->IsOpen())){
    ::Error("Input file not found : check your cut object","");
      }
  }

  AliRDHFCutsD0toKpi* RDHFD0toKpiCuts=new AliRDHFCutsD0toKpi();
  RDHFD0toKpiCuts = (AliRDHFCutsD0toKpi*)filecuts->Get("D0toKpiAnalysisCuts");
  if(!RDHFD0toKpiCuts){
    cout<<"Specific AliRDHFCutsD0toKpi not found"<<endl;
    return 0;
  }
  RDHFD0toKpiCuts->SetName("D0toKpiCuts");
    
  //CREATE THE TASK
  printf("CREATE TASK\n");

  // create the task
  AliAnalysisTaskSEBpmMass *task = new AliAnalysisTaskSEBpmMass("AliAnalysisTaskSEBpmMass",RDHFD0toKpiCuts);

  task->SetReadMC(bUseMCInfo);
  task->SetKillCandidates(killCandidates);
  task->SelectHIJINGOnly(isHIJINGonly);
  task->IsHIJINGAvailable(isHIJING);
  task->PerformRotation(performRotation);
  task->SetRotationAngle(nDegreePerRotation);
  task->SetNRotations(nNumberOfRotations);
  task->SetUseCentrality(useCentrality); // not used

  mgr->AddTask(task);

  // Create and connect containers for input/output
  usercomment = "_" + usercomment;

  TString outputfile = AliAnalysisManager::GetCommonFileName();

  outputfile += ":PWG3_D2H_BpmMass";
  outputfile += usercomment;
  
  // ------ input data ------
  TString input = "input";
  input += usercomment;
  TString output1 = "List";
  output1 += usercomment;
  TString output2 = "ListVar";
  output2 += usercomment;
  TString output3 = "ListMCVar";
  output3 += usercomment;
  TString output4 = "ListDSandB";
  output4 += usercomment;
  TString output5 = "ListDSonly";
  output5 += usercomment;
  TString output6 = "SelectionVariables";
  output6 += usercomment;
  TString output7 = "RotatedCandidates";
  output7 += usercomment;
  TString output8 = "Cuts";
  output8 += usercomment;
    
  AliAnalysisDataContainer *cinput0  =                    mgr->CreateContainer(input,TChain::Class(), AliAnalysisManager::kInputContainer);

 // ----- output data -----
  AliAnalysisDataContainer *coutputList =                    mgr->CreateContainer(output1,TList::Class(),AliAnalysisManager::kOutputContainer,outputfile.Data());
  AliAnalysisDataContainer *coutputListVar =                 mgr->CreateContainer(output2,TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputListMCVar =      mgr->CreateContainer(output3,TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputListDSandB =     mgr->CreateContainer(output4,TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputListDSonly =               mgr->CreateContainer(output5,TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputSelectionVariables =                   mgr->CreateContainer(output6,TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputRotatedCandidates =                   mgr->CreateContainer(output7,TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputCuts =              mgr->CreateContainer(output8,TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());

  mgr->ConnectInput(task,0,mgr->GetCommonInputContainer());
  mgr->ConnectOutput(task,1,coutputList);
  mgr->ConnectOutput(task,2,coutputListVar);
  mgr->ConnectOutput(task,3,coutputListMCVar);
  mgr->ConnectOutput(task,4,coutputListDSandB);
  mgr->ConnectOutput(task,5,coutputListDSonly);
  mgr->ConnectOutput(task,6,coutputSelectionVariables);
  mgr->ConnectOutput(task,7,coutputRotatedCandidates);
  mgr->ConnectOutput(task,8,coutputCuts);


  return task;
}
